apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-db-pvc
  namespace: retail-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# orders db deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-db-deployment
  namespace: retail-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-db
  template:
    metadata:
      labels:
        app: orders-db
    spec:
      containers:
      - name: postgres
        image: postgres:16.1
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits: 
            cpu: "1"
            memory: "2Gi"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orders-db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: orders-db-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: orders-db-config
              key: POSTGRES_USER
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - pg_isready -U orders_user -d orders || exit 1
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: orders-db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: orders-db-storage
        persistentVolumeClaim:
          claimName: orders-db-pvc
---
# service
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  namespace: retail-store
spec:
  selector:
    app: orders-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP