# helm secret
{{- range $name, $service := .Values.services }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-secret
  namespace: {{ $.Values.global.namespace }}
type: Opaque
stringData:
{{- if eq $name "catalog" }}
  RETAIL_CATALOG_PERSISTENCE_PASSWORD: {{ $.Values.dbPassword | quote }}
{{- end }}
{{- if eq $name "orders" }}
  RETAIL_ORDERS_PERSISTENCE_PASSWORD: {{ $.Values.dbPassword | quote }}
  RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD: {{ $.Values.dbPassword | quote }}
  _placeholder: "placeholder"
{{- end }}
{{- end }}