{{- range $name, $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    app: {{ $name }}
  ports:
  - name: http
    port: {{ $service.port }}
    targetPort: {{ $service.port }}
  type: ClusterIP
{{- end }}
