apiVersion: apps/v1 
kind: Deployment
metadata:
  name: catalog-deployment
  namespace: retail-store 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: retail-catalog:1.0.0
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: catalog-config
        - secretRef:
            name: catalog-secret
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10